In [2]:
import pandas as pd
import binascii

In [3]:
pd.set_option('display.max_colwidth', -1)

In [4]:
dataset = pd.read_csv("dropped.csv")

In [5]:
dataset.head(5)

1
0  Here is our forecast                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
1  Traveling to have a business meeting takes the fun out of the trip.  Especially if you have to prepare a presentation.  I would suggest holding the business plan meetings here then take a trip without any formal business meetings.  I would even try and get some honest opinions on whether a trip is even desired or necessary.As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about what is working and what is not.  Too often the presenter speaks and the others are quiet just waiting for their turn.   The meetings might be better if held in a round table discussion format.  My suggestion for where to go is Austin.  Play golf and rent a ski boat and jet ski's.  Flying somewhere takes too much time.
2  test successful.  way to go!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
3  Randy, Can you send me a schedule of the salary and level of everyone in the scheduling group.  Plus your thoughts on any changes that need to be made.  (Patti S for example)Phillip                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
4  Let's shoot for Tuesday at 11:45.

In [6]:
# number of letters in a shingle
k_shingles=5

shingle_sim=True
all_shingles=list() 
threshold=0.5

In [7]:
# Function to compute the set of k-shingles for an email
def get_k_shingles(email_text):
    letters = list(str(email_text).strip('[]" ').replace("'",""))
    #for i in range(len(letters) - k_shingles + 1):
        #print (letters[i:i+k_shingles])
    #print(letters)
    return sorted(set([binascii.crc32(str.encode("".join(letters[i:i+k_shingles]))) & 0xffffffff for i in range(len(letters) - k_shingles + 1)]))

#Function to compare two sets of k-shingles using Jaccard Similarity
def shingles_similarity(a, b):
    intersection = len(list(set(a).intersection(b)))
    union = (len(a) + len(b)) - intersection
    if union == 0:
        return 0.0
    return intersection / float(union)


In [8]:
#Iterates over the mails in the dataset and creates the shingles set for each mail. It appends every shingles set in shingles.
for row in dataset.iterrows():
    email_shingles=get_k_shingles(row[1].values)
    #print(email_shingles)
    if shingle_sim:
        all_shingles.append(email_shingles)
        #print(all_shingles)

#Prints the similarities between shingles sets whose value is > threshold
print("\n", "+++ SHINGLES +++","\n")
for i in range(len(all_shingles)):
    for j in range(len(all_shingles)):
        if i < j:
            value = shingles_similarity(all_shingles[i], all_shingles[j])
            if value > threshold:
                print("(mail " + str(i) + ", mail " + str(j) + "): " + str(value))


 +++ SHINGLES +++ 

(mail 0, mail 277): 0.9411764705882353
(mail 1, mail 286): 1.0
(mail 12, mail 13): 0.9963963963963964
(mail 17, mail 287): 1.0
(mail 23, mail 24): 0.9050632911392406
(mail 25, mail 26): 0.9980963259090044
(mail 28, mail 288): 1.0
(mail 30, mail 35): 0.5845323741007195
(mail 34, mail 35): 0.7072310405643739
(mail 39, mail 289): 1.0
(mail 41, mail 51): 0.9934776163652534
(mail 41, mail 57): 0.9931770987837437
(mail 50, mail 290): 0.9376218323586745
(mail 51, mail 57): 0.9931770987837437
(mail 61, mail 292): 0.8695884553714591
(mail 66, mail 71): 0.8197674418604651
(mail 67, mail 74): 0.8710801393728222
(mail 72, mail 293): 0.8297541238717709
(mail 80, mail 123): 0.5454545454545454
(mail 83, mail 294): 1.0
(mail 94, mail 105): 0.9806295399515739
(mail 94, mail 295): 0.9324644549763034
(mail 94, mail 296): 0.9143192488262911
(mail 105, mail 295): 0.9143192488262911
(mail 105, mail 296): 0.9324644549763034
(mail 116, mail 278): 0.833686120350771
(mail 124, mail 142): 0.

In [9]:
dataset.iloc[23]

1    ---------------------- Forwarded by Phillip K Allen/HOU/ECT on 09/28/2000 01:09 PM ---------------------------   \t\t\tFrom:  Phillip K Allen                           09/28/2000 10:56 AM\tLiane, As we discussed yesterday, I am concerned there may have been an attempt to manipulate the  El Paso San Juan monthly index.  It appears that a single buyer entered the marketplace on both September 26 and 27 and paid above market prices ($4.70-$4.80) for San Juan gas.  At the time of these trades, offers for physical gas at significantly (10 to 15 cents) lower prices were bypassed in order to establish higher trades to report into the index calculation.  Additionally, these trades are out of line with the associated financial swaps for San Juan. We have compiled a list of financial and physical trades executed from September 25 to September 27.  These are the complete list of trades from Enron Online (EOL), Enron's direct phone conversations, and three brokerage firms (Amerex, APB, and Pr

In [10]:
dataset.iloc[24]

1    Liane, As we discussed yesterday, I am concerned there has been an attempt to manipulate the  El Paso San Juan monthly index.  A single buyer entered the marketplace on both September 26 and 27 and paid above market prices ($4.70-$4.80) for San Juan gas with the intent to distort the index.  At the time of these trades, offers for physical gas at significantly (10 to 15 cents) lower prices were bypassed in order to establish higher trades to report into the index calculation.  Additionally, these trades are out of line with the associated financial swaps for San Juan. We have compiled a list of financial and physical trades executed from September 25 to September 27.  These are the complete list of trades from Enron Online (EOL), Enron's direct phone conversations, and three brokerage firms (Amerex, APB, and Prebon).  Please see the attached spreadsheet for a trade by trade list and a summary.  We have also included a summary of gas daily prices to illustrate the value of San Juan

In [11]:
# Count the number of shingles across all the emails.
all_shingles_counter=0
for email_shingles in all_shingles:
    for shingle in email_shingles:
        all_shingles_counter=all_shingles_counter+1
print (all_shingles_counter)

297461


In [12]:
# Check if integer n is a prime
from math import sqrt; from itertools import count, islice

def isPrime(n):
    return n > 1 and all(n%i for i in islice(count(2), int(sqrt(n)-1)))

In [13]:
i = 1
# Find first prime which is higher than the total number of shingles
while not isPrime(all_shingles_counter + i):
    i = i + 1
c = all_shingles_counter+i
c

297467

In [14]:
import random
import numpy as np

signature_sim=True
#Number of hashes in the MinHash step
num_hashes=100
#Matrix of signatures
signature_matrix = [0 for i in range(num_hashes)]

In [15]:
# Get as many pairs of parameters as the number of hash functions
def get_hash_coefficients():
    a = random.sample(range(0,2**23),num_hashes)
    b = random.sample(range(0,2**23),num_hashes)
    return a, b

# Compute the signature out of a set of shingles
def signature(email_shingles,a,b):
    #Track the lowest hash ID seen
    #Initialize 'min_hash' to be greater than the maximum possible value output by the hash
    min_hash = c + 1
    # The resulting minhash signature for this email
    signature = []
    # For each of the random hash functions...
    for i in range(num_hashes):
        for shingle in email_shingles:
            # Our random hash function will take the form of:
            #   h(x) = (a*x + b) % c
            # Where 'x' is the input value, 'a' and 'b' are random coefficients, and 'c' is
            # a prime number just greater than shingleNo.
            hash_code = (a[i] * shingle + b[i]) % c 
            if hash_code < min_hash:
                min_hash = hash_code
        signature.append(min_hash)
    #print (signature)
    return signature

# Compare two signatures
def compare_signatures( a, b):
    equal = 0
    for i in range(len(a)):
        if(a[i]==b[i]):
            equal += 1

    return equal/len(a)

In [16]:
for row in dataset.iterrows():
    a,b = get_hash_coefficients()
    # Get the shingles set for this email
    email_shingles=get_k_shingles(row[1].values)
    if signature_sim:
        #signature(email_shingles, a, b)
        signature_matrix = np.column_stack((signature_matrix, signature(email_shingles, a, b)))

In [17]:
signature_matrix = np.delete(signature_matrix,0,axis = 1)
signature_matrix.shape[1]
print(signature_matrix)
signature_matrix.shape

[[72944   152 27811 ...  1100  1179   133]
 [ 8608    77  4832 ...  1100  1179   133]
 [ 8608    77  4832 ...  1100   570   133]
 ...
 [   26     0    29 ...     1     5     2]
 [   26     0    29 ...     1     5     2]
 [   26     0    29 ...     1     5     2]]


(100, 500)

In [18]:
if signature_sim:
    print("\n", "+++ MIN-HASH +++","\n")
    for i in range(signature_matrix.shape[1]):
        for j in range(signature_matrix.shape[1]):
            if i < j:
                value = compare_signatures(np.squeeze(signature_matrix[:,i]), np.squeeze(signature_matrix[:,j]))
                if value > threshold:
                    print("(mail " + str(i) + ", mail " + str(j) + "): " + str(value))


 +++ MIN-HASH +++ 

(mail 1, mail 13): 0.63
(mail 1, mail 23): 0.51
(mail 1, mail 25): 0.63
(mail 1, mail 38): 0.63
(mail 1, mail 40): 0.63
(mail 1, mail 41): 0.6
(mail 1, mail 48): 0.63
(mail 1, mail 51): 0.63
(mail 1, mail 52): 0.61
(mail 1, mail 54): 0.54
(mail 1, mail 57): 0.63
(mail 1, mail 58): 0.63
(mail 1, mail 61): 0.63
(mail 1, mail 110): 0.63
(mail 1, mail 116): 0.63
(mail 1, mail 136): 0.63
(mail 1, mail 156): 0.63
(mail 1, mail 163): 0.63
(mail 1, mail 177): 0.63
(mail 1, mail 212): 0.63
(mail 1, mail 238): 0.63
(mail 1, mail 246): 0.58
(mail 1, mail 247): 0.63
(mail 1, mail 261): 0.63
(mail 1, mail 262): 0.63
(mail 1, mail 272): 0.63
(mail 1, mail 283): 0.63
(mail 1, mail 293): 0.63
(mail 1, mail 304): 0.63
(mail 1, mail 328): 0.63
(mail 1, mail 335): 0.63
(mail 1, mail 354): 0.59
(mail 1, mail 360): 0.63
(mail 1, mail 373): 0.63
(mail 1, mail 380): 0.63
(mail 1, mail 389): 0.63
(mail 1, mail 391): 0.63
(mail 1, mail 421): 0.63
(mail 1, mail 436): 0.63
(mail 1, mail 451)

(mail 30, mail 65): 0.51
(mail 30, mail 260): 0.58
(mail 31, mail 130): 0.53
(mail 31, mail 141): 0.53
(mail 31, mail 201): 0.53
(mail 31, mail 249): 0.53
(mail 31, mail 303): 0.53
(mail 31, mail 308): 0.68
(mail 31, mail 338): 0.53
(mail 32, mail 60): 0.93
(mail 32, mail 75): 0.94
(mail 32, mail 80): 0.58
(mail 32, mail 88): 0.81
(mail 32, mail 135): 0.57
(mail 32, mail 138): 0.51
(mail 32, mail 183): 0.71
(mail 32, mail 189): 0.72
(mail 32, mail 203): 0.65
(mail 32, mail 211): 0.91
(mail 32, mail 241): 0.53
(mail 32, mail 284): 0.52
(mail 32, mail 321): 0.97
(mail 32, mail 341): 0.93
(mail 32, mail 347): 0.57
(mail 32, mail 370): 0.95
(mail 32, mail 397): 0.98
(mail 32, mail 398): 0.98
(mail 32, mail 414): 0.55
(mail 32, mail 419): 0.66
(mail 32, mail 443): 0.58
(mail 32, mail 456): 0.66
(mail 33, mail 34): 0.58
(mail 33, mail 190): 0.52
(mail 33, mail 204): 0.69
(mail 33, mail 239): 0.69
(mail 33, mail 317): 0.66
(mail 34, mail 204): 0.58
(mail 34, mail 239): 0.58
(mail 34, mail 317

(mail 57, mail 58): 0.8
(mail 57, mail 61): 0.8
(mail 57, mail 110): 0.76
(mail 57, mail 116): 0.8
(mail 57, mail 136): 0.8
(mail 57, mail 156): 0.75
(mail 57, mail 163): 0.8
(mail 57, mail 177): 0.8
(mail 57, mail 212): 0.8
(mail 57, mail 238): 0.69
(mail 57, mail 246): 0.58
(mail 57, mail 247): 0.8
(mail 57, mail 261): 0.78
(mail 57, mail 262): 0.8
(mail 57, mail 272): 0.68
(mail 57, mail 283): 0.8
(mail 57, mail 293): 0.76
(mail 57, mail 304): 0.75
(mail 57, mail 328): 0.72
(mail 57, mail 335): 0.79
(mail 57, mail 354): 0.59
(mail 57, mail 360): 0.8
(mail 57, mail 373): 0.8
(mail 57, mail 380): 0.8
(mail 57, mail 389): 0.69
(mail 57, mail 391): 0.8
(mail 57, mail 421): 0.8
(mail 57, mail 436): 0.69
(mail 57, mail 451): 0.8
(mail 57, mail 452): 0.8
(mail 57, mail 464): 0.79
(mail 57, mail 474): 0.8
(mail 57, mail 483): 0.8
(mail 57, mail 485): 0.72
(mail 58, mail 61): 0.82
(mail 58, mail 110): 0.76
(mail 58, mail 116): 0.82
(mail 58, mail 136): 0.82
(mail 58, mail 156): 0.75
(mail 58

(mail 100, mail 251): 0.52
(mail 100, mail 291): 0.88
(mail 100, mail 311): 0.59
(mail 100, mail 366): 0.88
(mail 103, mail 119): 0.68
(mail 103, mail 235): 0.66
(mail 103, mail 324): 0.52
(mail 103, mail 362): 0.71
(mail 103, mail 427): 0.71
(mail 105, mail 174): 0.88
(mail 105, mail 263): 0.7
(mail 105, mail 290): 0.73
(mail 105, mail 319): 0.61
(mail 105, mail 381): 0.65
(mail 105, mail 393): 0.54
(mail 105, mail 430): 0.66
(mail 106, mail 237): 0.64
(mail 108, mail 118): 0.75
(mail 108, mail 123): 0.84
(mail 108, mail 126): 0.84
(mail 108, mail 132): 0.84
(mail 108, mail 162): 0.66
(mail 108, mail 172): 0.53
(mail 108, mail 176): 0.78
(mail 108, mail 215): 0.52
(mail 108, mail 218): 0.84
(mail 108, mail 220): 0.8
(mail 108, mail 275): 0.52
(mail 108, mail 276): 0.51
(mail 108, mail 302): 0.84
(mail 108, mail 336): 0.84
(mail 108, mail 349): 0.75
(mail 108, mail 350): 0.84
(mail 108, mail 377): 0.62
(mail 108, mail 388): 0.56
(mail 108, mail 390): 0.84
(mail 108, mail 425): 0.84
(ma

(mail 138, mail 183): 0.51
(mail 138, mail 189): 0.51
(mail 138, mail 203): 0.51
(mail 138, mail 211): 0.51
(mail 138, mail 321): 0.51
(mail 138, mail 341): 0.51
(mail 138, mail 347): 0.51
(mail 138, mail 370): 0.51
(mail 138, mail 397): 0.51
(mail 138, mail 398): 0.51
(mail 138, mail 443): 0.51
(mail 138, mail 456): 0.51
(mail 141, mail 201): 0.67
(mail 141, mail 249): 0.67
(mail 141, mail 303): 0.67
(mail 141, mail 308): 0.67
(mail 141, mail 338): 0.67
(mail 144, mail 175): 0.51
(mail 144, mail 279): 0.51
(mail 144, mail 294): 0.51
(mail 144, mail 316): 0.67
(mail 144, mail 332): 0.51
(mail 144, mail 438): 0.51
(mail 144, mail 466): 0.51
(mail 144, mail 480): 0.51
(mail 145, mail 164): 0.8
(mail 145, mail 165): 0.8
(mail 145, mail 199): 0.8
(mail 145, mail 223): 0.8
(mail 145, mail 267): 0.8
(mail 145, mail 282): 0.53
(mail 145, mail 323): 0.59
(mail 145, mail 386): 0.66
(mail 145, mail 392): 0.8
(mail 145, mail 404): 0.8
(mail 145, mail 429): 0.8
(mail 145, mail 439): 0.8
(mail 145,

(mail 196, mail 438): 0.51
(mail 199, mail 223): 0.88
(mail 199, mail 267): 0.88
(mail 199, mail 282): 0.53
(mail 199, mail 323): 0.59
(mail 199, mail 386): 0.66
(mail 199, mail 392): 0.91
(mail 199, mail 404): 0.83
(mail 199, mail 429): 0.86
(mail 199, mail 439): 0.83
(mail 199, mail 457): 0.8
(mail 201, mail 249): 0.81
(mail 201, mail 303): 0.86
(mail 201, mail 308): 0.76
(mail 201, mail 338): 0.69
(mail 201, mail 403): 0.64
(mail 201, mail 460): 0.53
(mail 203, mail 205): 0.57
(mail 203, mail 211): 0.65
(mail 203, mail 284): 0.52
(mail 203, mail 321): 0.65
(mail 203, mail 341): 0.65
(mail 203, mail 347): 0.57
(mail 203, mail 370): 0.65
(mail 203, mail 397): 0.65
(mail 203, mail 398): 0.65
(mail 203, mail 443): 0.58
(mail 203, mail 456): 0.65
(mail 204, mail 239): 0.89
(mail 204, mail 317): 0.66
(mail 204, mail 499): 0.55
(mail 205, mail 371): 0.81
(mail 205, mail 394): 0.65
(mail 207, mail 295): 0.52
(mail 207, mail 406): 0.65
(mail 209, mail 412): 0.59
(mail 211, mail 241): 0.53
(m

(mail 275, mail 276): 0.51
(mail 275, mail 302): 0.52
(mail 275, mail 336): 0.52
(mail 275, mail 350): 0.52
(mail 275, mail 377): 0.52
(mail 275, mail 388): 0.52
(mail 275, mail 390): 0.52
(mail 275, mail 406): 0.55
(mail 275, mail 425): 0.52
(mail 275, mail 428): 0.52
(mail 275, mail 441): 0.52
(mail 275, mail 445): 0.52
(mail 275, mail 465): 0.52
(mail 275, mail 478): 0.52
(mail 275, mail 486): 0.52
(mail 275, mail 497): 0.52
(mail 276, mail 302): 0.51
(mail 276, mail 336): 0.51
(mail 276, mail 350): 0.51
(mail 276, mail 377): 0.51
(mail 276, mail 388): 0.51
(mail 276, mail 390): 0.51
(mail 276, mail 424): 0.59
(mail 276, mail 425): 0.51
(mail 276, mail 428): 0.51
(mail 276, mail 441): 0.51
(mail 276, mail 445): 0.51
(mail 276, mail 465): 0.51
(mail 276, mail 478): 0.51
(mail 276, mail 486): 0.51
(mail 276, mail 497): 0.51
(mail 278, mail 388): 0.56
(mail 278, mail 390): 0.53
(mail 278, mail 497): 0.54
(mail 279, mail 294): 0.69
(mail 279, mail 316): 0.51
(mail 279, mail 332): 0.61
(

(mail 354, mail 360): 0.59
(mail 354, mail 373): 0.59
(mail 354, mail 380): 0.59
(mail 354, mail 389): 0.59
(mail 354, mail 391): 0.59
(mail 354, mail 408): 0.52
(mail 354, mail 421): 0.59
(mail 354, mail 436): 0.59
(mail 354, mail 451): 0.59
(mail 354, mail 452): 0.59
(mail 354, mail 464): 0.59
(mail 354, mail 474): 0.59
(mail 354, mail 483): 0.59
(mail 354, mail 485): 0.59
(mail 356, mail 376): 0.59
(mail 356, mail 400): 0.59
(mail 357, mail 368): 0.68
(mail 360, mail 373): 0.88
(mail 360, mail 380): 0.83
(mail 360, mail 389): 0.69
(mail 360, mail 391): 0.88
(mail 360, mail 421): 0.88
(mail 360, mail 436): 0.69
(mail 360, mail 451): 0.88
(mail 360, mail 452): 0.81
(mail 360, mail 464): 0.79
(mail 360, mail 474): 0.85
(mail 360, mail 483): 0.8
(mail 360, mail 485): 0.72
(mail 361, mail 378): 0.54
(mail 361, mail 434): 0.51
(mail 361, mail 446): 0.54
(mail 361, mail 482): 0.52
(mail 361, mail 490): 0.54
(mail 362, mail 427): 0.8
(mail 370, mail 397): 0.95
(mail 370, mail 398): 0.95
(ma

In [19]:
dataset.iloc[337]

1    Jacques,The amounts needed to fill in the blanks on Exhibit "B" are as follows:Kipp Flores-Total Contract was $23,600 but $2,375 was paid and only $21,225 is outstanding.Kohutek- $2,150 Cuatro- $37,800George & Larry paid $3,500 for the appraisal and I agreed to reimburse this amount.The total cash that Keith and I will pay the Sellers is $5,875 ($3,500 appraisal and $2,375 engineering).    I couldn't find any reference to this cash consideration to be paid by the buyers.Let me know if I need to do anything else before you can forward this to the  sellers to be executed.Phillip
Name: 337, dtype: object

In [20]:
dataset.iloc[354]

1    Reagan,Thank you for the quick response on the bid for the residence.  Below is a list of questions on the specs:1.  Is the framing Lumber #2 yellow pine?  Wouldn't fir or spruce warp less and cost about the same?2.  What type of floor joist would be used?  2x12 or some sort of factory joist?3.  What type for roof framing?  On site built rafters? or engineered trusses?4.  Are you planning for insulation between floors to dampen sound?  What type of insulation in floors and ceiling?  Batts or blown?  Fiberglass or Cellulose?5.  Any ridge venting or other vents (power or turbine)?6. Did you bid for interior windows to have trim on 4 sides?  I didn't know the difference between an apron and a stool.7.  Do you do anything special under the upstairs tile floors to prevent cracking?  Double plywood or hardi board underlay?8.  On the stairs, did you allow for a bannister?  I was thinking a partial one out of iron.  Only about 5 feet.9.  I did not label it on the plan, but I was intending

In [21]:
from operator import itemgetter
import random as rnd

len_buckets = 101#choice a prime number
hash_table = [[] for i in range(len_buckets)]

# For the buckets
def initialize_array_bucket(bands):
    global len_buckets
    array_buckets = []
    for band in range(bands):
        array_buckets.append([[] for i in range(len_buckets)])
    return array_buckets

# To generate hash function
def generate_hash_functions(n):
    hash_funcs = []

    for i in range(n):
        var = rnd.randint(0,1000)
        cons = rnd.randint(0,1000)
        hash_funcs.append([var,cons])
    return hash_funcs

def euclidean_distance(x,y,r=2.0):
    try:
        
        return sum(((x[i] - y[i]) ** r) for i in range(len(x))) ** (1.0/r)
    
    except (ValueError,ZeroDivisionError):
        print ('Please, enter only even values for "r > 0".')
    except IndexError:
        print ('Please, the sets must have the same size.')

def cosine_distance(x,y):
    prodAB = sum([x[i]*y[i] for i in range(len(x))])
    zeros = [0 for i in range(len(x))]
    A = euclidean_distance(x,zeros)
    B = euclidean_distance(y,zeros)
    return prodAB / (A*B)

#4. Choose a threshold t that defines how similar documents have to be.
#5. Construct candidate pairs by applying the LSH technique of Section 3.4.1.
#6. Examine each candidate pair's signatures and determine whether the fraction
#of components in which they agree is at least t.
#Pick a number of bands b and a number of rows r such that br = n,
#and the threshold t is approximately (1/b)^1/r
#WARNING ==> b*r = n
def apply_LSH_technique(SIG,t,bands=4,rows=3):
    if bands * rows != len(SIG):
        raise 'bands*rows must be equals to n :: bands*rows = n !!!'
    #print SIG
    #print

    array_buckets = initialize_array_bucket(bands)
    #print array_buckets

    hash_funcs = generate_hash_functions(bands)


    candidates = {}
    
    i = 0
    for b in range(bands):
        buckets = array_buckets[b]        
        band = SIG[i:i+rows,:]
        for col in range(band.shape[1]):
            #print band[:,col]

            #randomly generate
            #key = 0
            #for row in xrange(rows):
            #    func = hash_funcs[row]
            #    key += hash_minHash(band[row,col],func[0],func[1],len(buckets))
            #key = int((key+sum(band[:,col])) % len(buckets))
            #randomly generate
            #func = hash_funcs[b]

            #key = int(hash_minHash(sum(band[:,col]),func[0],func[1],len(buckets)))
            #print 'key->',key
            
            key = int(sum(band[:,col]) % len(buckets))
            
            buckets[key].append(col)
        i = i+rows

        #print 'buckets #',b,buckets
        for item in buckets:
            if len(item) > 1:
                pair = (item[0], item[1])
                if pair not in candidates:
                    A = SIG[:,item[0]]
                    B = SIG[:,item[1]]
                    similarity = cosine_distance(A,B)
                    if similarity >= t:
                        candidates[pair] = similarity


    #print 
    sort = sorted(candidates.items(),key=itemgetter(1), reverse=True)
    #print sort
    #print 
    return candidates,sort

In [32]:
#Calling the LSH function
t=0.7
b=20
r=5
candidates,sort = apply_LSH_technique(signature_matrix,t,b,r)

print("There are " + str(len(candidates)) + " candidate pairs\n")

print(candidates)

There are 595 candidate pairs

{(53, 100): 0.7450524160682681, (4, 33): 0.7731955679310127, (91, 127): 0.7727122068544254, (42, 61): 0.837609749423426, (239, 245): 0.9629689347200379, (5, 172): 0.864101444688766, (111, 125): 0.8492163260216821, (49, 69): 0.74791619513695, (38, 94): 0.8221433730473484, (129, 130): 0.9870937479071795, (133, 232): 0.7472176950007987, (36, 88): 0.7689156810069053, (10, 27): 0.8363186667206938, (46, 159): 0.8267959000974818, (9, 195): 0.7278336273222596, (15, 45): 0.7651127376935659, (163, 331): 0.9104993750226841, (90, 109): 0.8307242823677572, (40, 113): 0.8643902215257245, (156, 313): 0.851324310743302, (117, 123): 0.8320974288633355, (193, 396): 0.9324918880468938, (23, 93): 0.8986432627773556, (202, 279): 0.8077556134889496, (198, 233): 0.7432933172079307, (71, 251): 0.829701874654428, (134, 158): 0.7939594194923139, (0, 41): 0.7654179028664212, (12, 72): 0.7633552422315979, (32, 103): 0.8966234779069173, (206, 207): 0.8024178078674643, (95, 365): 0.75

In [30]:
dataset.iloc[239]

1    Mary, I transferred $10,000 out of the checking account on Monday 2/28/00.  I will call you Monday or Tuesday to see what is new.Phillip
Name: 239, dtype: object

In [31]:
dataset.iloc[245]

1    Should I appeal to Skilling.---------------------- Forwarded by Phillip K Allen/HOU/ECT on 02/15/2000 12:52 PM ---------------------------Lee Wright@ENRON02/15/2000 10:48 AMTo: Phillip K Allen/HOU/ECT@ECTcc: Amelia Alder/OTS/Enron@ENRON Subject: Storage of Cycles at the Body ShopPhillip -I applaud you for using your cycle as daily transportation.  Saves on gas, pollution and helps keep you strong and healthy.  Enron provides bike racks in the front of the building for requests such as this.  Phillip, I wish we could accommodate this request; however, The Body Shop does not have the capacity nor can assume the responsibility for storing cycles on a daily basis.  If you bring a very good lock you should be able to secure the bike at the designated outside racks.  Keep Pedalling - Lee
Name: 245, dtype: object